default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: olumeca_development

test:
  <<: *default
  database: olumeca_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5
