default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: unicode

development:
  <<: *default
  database: olumeca_development

test:
  <<: *default
  database: olumeca_test

production:
  <<: *default
  database: olumeca_production
  username: <%= ENV['OLUMECA_DATABASE_USER'] %>
  password: <%= ENV['OLUMECA_DATABASE_PASSWORD'] %>
  host: <%= ENV['OLUMECA_DATABASE_HOST'] %>