development:
  secret_key_base: aaad86c18142499ee97af745a05f611e6077e41bfb67f3458dd1b9c353903d4c10cba0fe42a496a0f2d50bb59368555a91eac66b2f3525a033bbf2bb60b1a423
  recaptcha_site_key: 6Lc4MrYpAAAAAOPhiptyCFYycMGGm24kchjt4hma
  recaptcha_secret_key: 6Lc4MrYpAAAAADQPRe84JVkqjyFJkM-YKbXeWjlH

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>